---
- hosts: all
  gather_facts: no
  tasks:
  - name: install aide
    ansible.builtin.package:
      name: aide
      state: present

  - name: copy aide.conf to root's home for testing
    ansible.builtin.copy:
      src: files/aide.conf
      dest: /root
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: initial run of aide
    command: aide -i -c /root/aide.conf 
    args:
      creates: /var/lib/aide/aide.db.new.gz
    tags:
      test
